Revert protect consul service by choregraphie
The weight attribute does not exist in systemd_unit resource
causing error
    "NoMethodError: undefined method `weight'"

It seems to exist in resource systemd_service_drop_in - to be
pushed in another patch. In the meantime, reverting to avoid
breakage.